[package]
name = "zkvm_wasm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.80"
wasmi = {version = "0.31.2", default-features=false}

[profile.release]
strip = true
panic = "abort"
